AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Template to create DynamoDB table called Productos with ProductoID as the partition key.

Parameters:
  DynamoDBName:
    Description: "Lista de precios"
    Type: String
    Default: "ProductosNuevos"

Resources:
  ProductosTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref DynamoDBName
      AttributeDefinitions:
        - AttributeName: ProductoID
          AttributeType: S
      KeySchema:
        - AttributeName: ProductoID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: Name
          Value: !Ref DynamoDBName

