AWSTemplateFormatVersion: '2010-09-09'

Description:
  Template to create the S3 bucket, CloudFront, DynamoDB, ApiGateway, and Lambda for the Application layer

  Parameters:

  DynamoDBName:
    Description: "Nombre de la tabla DynamoDB para la tienda de libros"
    Type: String
    Default: "Productos"

  # DynamoDB Table
  
  ProductsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref DynamoDBName
      AttributeDefinitions:
        - AttributeName: ProductoID
          AttributeType: S
      KeySchema:
        - AttributeName: ProductoID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: "Name"
          Value: !Ref 'ProductsTable'