tasks:
  - name: aws-cli
    init: |          
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
    
  - name: flask-python
    command: |
      cd python-container
      pip install flask
      pip install flask-cors
      pip install boto3
      pip install python-dotenv
      cd $THEIA_WORKSPACE_ROOT
